"""
Enhanced Report Generator for Economic Intelligence Agent
ASCII visualizations, MD/HTML/JSON output, historical comparison
Extracted from analysis_engine.py and expanded with quant/risk/sentiment sections.
"""

import json
import os
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ── ASCII Visualization Helpers ──────────────────────────────────

SPARK_CHARS = "▁▂▃▄▅▆▇█"

def sparkline(values: List[float]) -> str:
    """Generate ASCII sparkline from numeric values"""
    if not values:
        return ""
    mn, mx = min(values), max(values)
    rng = mx - mn or 1
    return "".join(SPARK_CHARS[min(int((v - mn) / rng * 7), 7)] for v in values)


def hbar(label: str, value: float, max_val: float, width: int = 20) -> str:
    """Horizontal bar chart row"""
    filled = int(value / max_val * width) if max_val > 0 else 0
    bar = "█" * filled + "░" * (width - filled)
    return f"{label:>12s} |{bar}| {value:.1f}"


def mini_heatmap_row(label: str, values: Dict[str, float]) -> str:
    """Single row of text-based correlation heatmap"""
    cells = []
    for _, v in values.items():
        if v >= 0.7:
            cells.append("🟩")
        elif v >= 0.3:
            cells.append("🟨")
        elif v >= -0.3:
            cells.append("⬜")
        elif v >= -0.7:
            cells.append("🟧")
        else:
            cells.append("🟥")
    return f"{label:>6s} " + " ".join(cells)


# ── Report Generator ─────────────────────────────────────────────

class EnhancedReportGenerator:
    """Generate reports in Markdown, HTML, or JSON with rich visualizations"""

    def __init__(self, output_dir: str = "reports"):
        self.output_dir = output_dir

    # ── Markdown ─────────────────────────────────────────────────

    def generate_markdown(self, analysis: Dict, data: Dict,
                          quant: Optional[Dict] = None,
                          risk: Optional[Dict] = None,
                          sentiment: Optional[Dict] = None,
                          alerts: Optional[List[Dict]] = None,
                          previous: Optional[Dict] = None) -> str:
        """Generate comprehensive markdown report"""
        ts = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
        sections = []

        sections.append(f"# Global Economic Intelligence Report\n\n**Generated:** {ts}\n\n---\n")

        # Executive summary
        sections.append(self._md_executive_summary(analysis))

        # Market overview
        sections.append(self._md_market_overview(analysis, data))

        # Quantitative metrics
        if quant:
            sections.append(self._md_quant_section(quant))

        # Risk metrics
        if risk:
            sections.append(self._md_risk_section(risk))

        # Sentiment summary
        if sentiment:
            sections.append(self._md_sentiment_section(sentiment))

        # Key events
        sections.append(self._md_key_events(analysis))

        # Cross-asset analysis
        sections.append(self._md_cross_asset(analysis))

        # Risk assessment
        sections.append(self._md_risk_assessment(analysis))

        # Alerts
        if alerts:
            sections.append(self._md_alerts(alerts))

        # Outlook
        sections.append(self._md_outlook(analysis))

        # Trade setups
        sections.append(self._md_trade_setups(analysis))

        # Raw data snapshot
        sections.append(self._md_data_snapshot(data))

        # Historical comparison
        if previous:
            sections.append(self._md_historical_comparison(analysis, previous))

        sections.append("\n---\n*This report is generated by AI and should not be considered financial advice.*\n")

        return "\n".join(sections)

    def _md_executive_summary(self, analysis: Dict) -> str:
        es = analysis.get("executive_summary", {})
        risks = es.get("primary_risk_factors", [])
        opps = es.get("primary_opportunities", [])
        return f"""## Executive Summary

**Market Tone:** {es.get('market_tone', 'N/A').upper()}

**Key Theme:** {es.get('key_theme', 'N/A')}

### Primary Risk Factors
{self._bullets(risks)}

### Primary Opportunities
{self._bullets(opps)}

---
"""

    def _md_market_overview(self, analysis: Dict, data: Dict) -> str:
        mo = analysis.get("market_overview", {})
        lines = ["## Market Overview\n"]
        for section in ("equities", "bonds", "crypto", "forex"):
            d = mo.get(section, {})
            if d:
                lines.append(f"### {section.title()}")
                for k, v in d.items():
                    lines.append(f"- **{k.replace('_', ' ').title()}:** {v}")
                lines.append("")
        lines.append("---\n")
        return "\n".join(lines)

    def _md_quant_section(self, quant: Dict) -> str:
        lines = ["## Quantitative Metrics\n"]
        # Yield curve
        yc = quant.get("yield_curve", {})
        if yc:
            spread = yc.get("spread_2y10y")
            inv = yc.get("inverted", False)
            lines.append(f"### Yield Curve")
            lines.append(f"- **2Y-10Y Spread:** {spread}%" if spread is not None else "- **2Y-10Y Spread:** N/A")
            lines.append(f"- **Inverted:** {'Yes ⚠️' if inv else 'No'}")
            curve = yc.get("curve", {})
            if curve:
                tenors = ["3M", "6M", "1Y", "2Y", "3Y", "5Y", "7Y", "10Y", "20Y", "30Y"]
                vals = [curve.get(t) for t in tenors if t in curve]
                if vals:
                    lines.append(f"- **Curve Shape:** {sparkline(vals)}")
            lines.append("")

        # Technical signals
        ts = quant.get("technical_signals", {})
        if ts:
            lines.append("### Technical Signals")
            lines.append("| Symbol | Price | Change | Signal |")
            lines.append("|--------|-------|--------|--------|")
            for sym, sig in ts.items():
                lines.append(f"| {sym} | ${sig.get('price', 0):,.2f} | {sig.get('change_24h', 0):+.1f}% | {sig.get('signal', 'N/A')} |")
            lines.append("")

        # Market regime
        mr = quant.get("market_regime", {})
        if mr:
            lines.append("### Market Regime")
            for sym, info in mr.items():
                lines.append(f"- **{sym}:** {info.get('signal', 'N/A')} ({info.get('daily_change', 0):+.2f}%)")
            lines.append("")

        lines.append("---\n")
        return "\n".join(lines)

    def _md_risk_section(self, risk: Dict) -> str:
        lines = ["## Risk Metrics\n"]
        lines.append(f"**Overall Risk Level:** {risk.get('overall_risk_level', 'N/A').upper()}\n")

        var = risk.get("value_at_risk", {})
        if var:
            lines.append("### Value at Risk (95%)")
            for portfolio, metrics in var.items():
                lines.append(f"**{portfolio}:**")
                for k, v in metrics.items():
                    lines.append(f"- {k.replace('_', ' ').title()}: {v}%" if v is not None else f"- {k}: N/A")
            lines.append("")

        stress = risk.get("stress_tests", [])
        if stress:
            lines.append("### Stress Test Results")
            lines.append("| Scenario | P&L | P&L % |")
            lines.append("|----------|-----|-------|")
            for s in stress:
                lines.append(f"| {s['description']} | ${s['total_pnl']:,.0f} | {s['pnl_pct']:+.1f}% |")
            lines.append("")

        lines.append("---\n")
        return "\n".join(lines)

    def _md_sentiment_section(self, sentiment: Dict) -> str:
        lines = ["## Sentiment Analysis\n"]

        fg = sentiment.get("fear_greed", {})
        if fg:
            val = fg.get("value", 50)
            label = fg.get("label", "neutral")
            bar_len = int(val / 100 * 20)
            bar = "█" * bar_len + "░" * (20 - bar_len)
            lines.append(f"### Fear & Greed Index: {val:.0f}/100 ({label})")
            lines.append(f"`[{bar}]`\n")
            comps = fg.get("components", {})
            for name, score in comps.items():
                lines.append(f"- {name.replace('_', ' ').title()}: {score:.1f}")
            lines.append("")

        ns = sentiment.get("news_sentiment", {})
        if ns:
            lines.append("### News Sentiment")
            lines.append(f"- **Overall:** {ns.get('label', 'N/A')} (score: {ns.get('compound', 0):.3f})")
            lines.append(f"- **Bullish/Bearish/Neutral:** {ns.get('positive_pct', 0)}% / {ns.get('negative_pct', 0)}% / {ns.get('neutral_pct', 0)}%")
            lines.append("")

        cs = sentiment.get("crowd_sentiment", {})
        if cs:
            lines.append("### Crowd Sentiment (Reddit)")
            lines.append(f"- **Score:** {cs.get('score', 0):.3f} ({cs.get('label', 'N/A')})")
            lines.append(f"- **Volume:** {cs.get('volume', 0)} posts, {cs.get('total_engagement', 0)} engagement")
            lines.append("")

        lines.append("---\n")
        return "\n".join(lines)

    def _md_key_events(self, analysis: Dict) -> str:
        events = analysis.get("key_events", [])
        if not events:
            return "## Key Events & Catalysts\n\nNo major events identified.\n\n---\n"
        lines = ["## Key Events & Catalysts\n"]
        for i, e in enumerate(events, 1):
            lines.append(f"### {i}. {e.get('event', 'Unknown')}")
            lines.append(f"- **Impact:** {e.get('impact', 'N/A')}")
            lines.append(f"- **Affected Assets:** {', '.join(e.get('affected_assets', []))}")
            lines.append(f"- **Implication:** {e.get('market_implication', 'N/A')}\n")
        lines.append("---\n")
        return "\n".join(lines)

    def _md_cross_asset(self, analysis: Dict) -> str:
        items = analysis.get("cross_asset_analysis", [])
        if not items:
            return "## Cross-Asset Analysis\n\nNo significant patterns.\n\n---\n"
        lines = ["## Cross-Asset Analysis\n"]
        for a in items:
            lines.append(f"### {a.get('observation', 'Observation')}")
            lines.append(f"- **Assets:** {', '.join(a.get('assets_involved', []))}")
            lines.append(f"- **Historical Context:** {a.get('historical_context', 'N/A')}")
            lines.append(f"- **Implications:** {a.get('implications', 'N/A')}\n")
        lines.append("---\n")
        return "\n".join(lines)

    def _md_risk_assessment(self, analysis: Dict) -> str:
        ra = analysis.get("risk_assessment", {})
        lines = ["## Risk Assessment\n"]
        for r in ra.get("systemic_risks", []):
            lines.append(f"### {r.get('risk', 'Risk')}")
            lines.append(f"- **Severity:** {r.get('severity', 'N/A')}")
            lines.append(f"- **Probability:** {r.get('probability', 'N/A')}")
            lines.append(f"- **Triggers:** {', '.join(r.get('trigger_events', []))}\n")
        lines.append(f"**Tail Risks:** {'; '.join(ra.get('tail_risks', ['None']))}\n")
        lines.append(f"**Hedging:** {ra.get('hedging_considerations', 'N/A')}\n")
        lines.append("---\n")
        return "\n".join(lines)

    def _md_alerts(self, alerts: List[Dict]) -> str:
        if not alerts:
            return ""
        icons = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}
        lines = ["## Active Alerts\n"]
        for a in alerts:
            icon = icons.get(a.get("severity", ""), "⚪")
            lines.append(f"- {icon} **[{a.get('severity', '').upper()}]** {a.get('message', '')}")
        lines.append("\n---\n")
        return "\n".join(lines)

    def _md_outlook(self, analysis: Dict) -> str:
        o = analysis.get("outlook", {})
        kl = o.get("key_levels_to_watch", {})
        cats = o.get("catalysts_to_monitor", [])
        return f"""## Outlook & Forecasts

### Immediate (1-7 Days)
{o.get('immediate_1_7_days', 'N/A')}

### Short-Term (1-4 Weeks)
{o.get('short_term_1_4_weeks', 'N/A')}

### Medium-Term (1-6 Months)
{o.get('medium_term_1_6_months', 'N/A')}

### Key Levels to Watch
{self._dict_to_md(kl)}

### Catalysts to Monitor
{self._bullets(cats)}

---
"""

    def _md_trade_setups(self, analysis: Dict) -> str:
        setups = analysis.get("trade_setups", [])
        if not setups:
            return "## Trade Setups\n\nNo setups identified.\n\n---\n"
        lines = ["## Trade Setups\n"]
        for i, s in enumerate(setups, 1):
            lines.append(f"### Setup {i}: {s.get('idea', '')}")
            lines.append(f"- **Rationale:** {s.get('rationale', 'N/A')}")
            lines.append(f"- **Risk/Reward:** {s.get('risk_reward', 'N/A')}")
            lines.append(f"- **Timeframe:** {s.get('timeframe', 'N/A')}\n")
        lines.append("---\n")
        return "\n".join(lines)

    def _md_data_snapshot(self, data: Dict) -> str:
        from utils import format_price, format_percent, format_number
        lines = ["## Raw Market Data Snapshot\n"]

        # Crypto table
        crypto = data.get("crypto", {}).get("top_coins", [])
        if crypto:
            lines.append("### Top Cryptocurrencies")
            lines.append("| Symbol | Price | 24h Change | Market Cap |")
            lines.append("|--------|-------|------------|------------|")
            for c in crypto[:10]:
                sym = c.symbol if hasattr(c, "symbol") else c.get("symbol", "?")
                price = c.price if hasattr(c, "price") else c.get("price", 0)
                change = c.change_percent_24h if hasattr(c, "change_percent_24h") else c.get("change_percent_24h", 0)
                mcap = c.market_cap if hasattr(c, "market_cap") else c.get("market_cap", 0)
                lines.append(f"| {sym} | {format_price(price)} | {format_percent(change)} | ${format_number(mcap)} |")
            lines.append("")

        # Indices
        indices = data.get("equities", {}).get("indices", [])
        if indices:
            lines.append("### Major Indices")
            lines.append("| Index | Price | Change |")
            lines.append("|-------|-------|--------|")
            for idx in indices[:10]:
                sym = idx.symbol if hasattr(idx, "symbol") else idx.get("symbol", "?")
                price = idx.price if hasattr(idx, "price") else idx.get("price", 0)
                change = idx.change_percent_24h if hasattr(idx, "change_percent_24h") else idx.get("change_percent_24h", 0)
                lines.append(f"| {sym} | {format_price(price)} | {format_percent(change)} |")
            lines.append("")

        lines.append("---\n")
        return "\n".join(lines)

    def _md_historical_comparison(self, current: Dict, previous: Dict) -> str:
        lines = ["## Historical Comparison\n"]
        curr_tone = current.get("executive_summary", {}).get("market_tone", "N/A")
        prev_tone = previous.get("summary", {}).get("executive_summary", {}).get("market_tone", "N/A")
        if curr_tone != prev_tone:
            lines.append(f"- **Market Tone Change:** {prev_tone} → {curr_tone}")
        else:
            lines.append(f"- **Market Tone:** Unchanged ({curr_tone})")

        prev_ts = previous.get("timestamp", "N/A")
        lines.append(f"- **Compared to:** {prev_ts}")
        lines.append("\n---\n")
        return "\n".join(lines)

    # ── HTML ─────────────────────────────────────────────────────

    def generate_html(self, analysis: Dict, data: Dict, **kwargs) -> str:
        """Generate HTML report with inline CSS"""
        md = self.generate_markdown(analysis, data, **kwargs)
        # Simple MD→HTML conversion (basic — no external dep needed)
        html_body = self._md_to_html(md)
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Economic Intelligence Report — {datetime.now().strftime('%Y-%m-%d')}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #0d1117; color: #c9d1d9; line-height: 1.6; }}
  h1 {{ color: #58a6ff; border-bottom: 2px solid #30363d; padding-bottom: 10px; }}
  h2 {{ color: #79c0ff; margin-top: 30px; border-bottom: 1px solid #21262d; padding-bottom: 5px; }}
  h3 {{ color: #d2a8ff; }}
  table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
  th, td {{ border: 1px solid #30363d; padding: 8px 12px; text-align: left; }}
  th {{ background: #161b22; color: #58a6ff; }}
  tr:nth-child(even) {{ background: #161b22; }}
  code {{ background: #161b22; padding: 2px 6px; border-radius: 3px; font-family: 'Fira Code', monospace; }}
  hr {{ border: none; border-top: 1px solid #30363d; margin: 20px 0; }}
  strong {{ color: #e6edf3; }}
  a {{ color: #58a6ff; text-decoration: none; }}
  ul {{ padding-left: 20px; }}
  li {{ margin: 4px 0; }}
</style>
</head>
<body>
{html_body}
</body>
</html>"""

    @staticmethod
    def _md_to_html(md: str) -> str:
        """Minimal markdown to HTML converter (no external deps)"""
        import re
        lines = md.split("\n")
        html_lines = []
        in_table = False
        in_list = False

        for line in lines:
            stripped = line.strip()

            # Headings
            if stripped.startswith("# "):
                html_lines.append(f"<h1>{stripped[2:]}</h1>")
            elif stripped.startswith("## "):
                html_lines.append(f"<h2>{stripped[3:]}</h2>")
            elif stripped.startswith("### "):
                html_lines.append(f"<h3>{stripped[4:]}</h3>")
            elif stripped.startswith("---"):
                html_lines.append("<hr>")
            # Table
            elif stripped.startswith("|"):
                if "|---" in stripped or "|:--" in stripped:
                    continue
                cells = [c.strip() for c in stripped.split("|")[1:-1]]
                if not in_table:
                    html_lines.append("<table><tr>")
                    html_lines.append("".join(f"<th>{c}</th>" for c in cells))
                    html_lines.append("</tr>")
                    in_table = True
                else:
                    html_lines.append("<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>")
            else:
                if in_table:
                    html_lines.append("</table>")
                    in_table = False
                # List items
                if stripped.startswith("- "):
                    if not in_list:
                        html_lines.append("<ul>")
                        in_list = True
                    content = stripped[2:]
                    # Bold
                    content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', content)
                    html_lines.append(f"<li>{content}</li>")
                else:
                    if in_list:
                        html_lines.append("</ul>")
                        in_list = False
                    if stripped:
                        content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', stripped)
                        content = re.sub(r'`(.+?)`', r'<code>\1</code>', content)
                        html_lines.append(f"<p>{content}</p>")

        if in_table:
            html_lines.append("</table>")
        if in_list:
            html_lines.append("</ul>")

        return "\n".join(html_lines)

    # ── JSON ─────────────────────────────────────────────────────

    def generate_json(self, analysis: Dict, data: Dict, **kwargs) -> str:
        """Generate machine-readable JSON report"""
        report = {
            "generated_at": datetime.now().isoformat(),
            "analysis": analysis,
            "quant": kwargs.get("quant", {}),
            "risk": kwargs.get("risk", {}),
            "sentiment": kwargs.get("sentiment", {}),
            "alerts": kwargs.get("alerts", []),
        }
        return json.dumps(report, indent=2, default=str)

    # ── Save ─────────────────────────────────────────────────────

    def save_report(self, content: str, filename: Optional[str] = None, fmt: str = "markdown") -> str:
        os.makedirs(self.output_dir, exist_ok=True)
        ext = {"markdown": "md", "html": "html", "json": "json"}.get(fmt, "md")
        if filename is None:
            ts = datetime.now().strftime("%Y%m%d_%H%M")
            filename = f"economic_report_{ts}.{ext}"
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        return filepath

    # ── Helpers ───────────────────────────────────────────────────

    @staticmethod
    def _bullets(items: List[str]) -> str:
        if not items:
            return "- None identified"
        return "\n".join(f"- {item}" for item in items)

    @staticmethod
    def _dict_to_md(d: Dict) -> str:
        if not d:
            return "N/A"
        return "\n".join(f"- **{k.replace('_', ' ').title()}:** {v}" for k, v in d.items())
